FROM saltstack_base:ubuntu

RUN apt-get update && apt-get clean && \
  rm -rf /var/lib/apt/lists/*

RUN echo "master: master" >> /etc/salt/minion.d/master.conf

RUN mkdir -p /etc/services.d/salt
COPY ./templates/services/ubuntu/run-master /etc/services.d/salt/run
COPY ./templates/services/ubuntu/finish /etc/services.d/salt/
COPY ./templates/scripts/salt-reload-config /usr/local/bin
RUN chmod +x /usr/local/bin/salt-reload-config
