version: 2
jobs:
  test:
    docker:
      - image: python:3.6

    steps:
      - checkout
      - run:
          name: Setup Pipenv
          command: |
              pip install pipenv==2018.05.18
      - run:
          name: Test Flake8
          command: |
              make test-style
  publish-latest:
    docker:
      - image: circleci/buildpack-deps:18.04
    steps:
      - setup_remote_docker
      - checkout
      - run:
          name: Build Saltmaster Container
          command: |
              docker build -t appliedblockchain/saltmaster .
      - run:
          name: Push Container DockerHub
          command: |
              echo "$DOCKERHUB_PASS" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
              docker push appliedblockchain/saltmaster:latest

workflows:
  version: 2
  test:
    jobs:
      - test
      - publish-latest:
          requires:
            - test
          filters:
            branches:
              only: master
